// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dining_session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiningSession = `-- name: CreateDiningSession :one
INSERT INTO dining_sessions (
    table_id,
    session_type_id,
    created_by,
    guest_count,
    status,
    start_time,
    expires_at,
    price_per_guest,
    total_amount
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, table_id, session_type_id, created_by, guest_count, status, start_time, expires_at, price_per_guest, total_amount, created_at, updated_at
`

type CreateDiningSessionParams struct {
	TableID       pgtype.UUID        `json:"table_id"`
	SessionTypeID pgtype.UUID        `json:"session_type_id"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	GuestCount    int32              `json:"guest_count"`
	Status        string             `json:"status"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PricePerGuest pgtype.Numeric     `json:"price_per_guest"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
}

func (q *Queries) CreateDiningSession(ctx context.Context, arg CreateDiningSessionParams) (DiningSession, error) {
	row := q.db.QueryRow(ctx, createDiningSession,
		arg.TableID,
		arg.SessionTypeID,
		arg.CreatedBy,
		arg.GuestCount,
		arg.Status,
		arg.StartTime,
		arg.ExpiresAt,
		arg.PricePerGuest,
		arg.TotalAmount,
	)
	var i DiningSession
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.SessionTypeID,
		&i.CreatedBy,
		&i.GuestCount,
		&i.Status,
		&i.StartTime,
		&i.ExpiresAt,
		&i.PricePerGuest,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const extendSession = `-- name: ExtendSession :one
UPDATE dining_sessions
SET expires_at = $2, status = 'active', updated_at = NOW()
WHERE id = $1
RETURNING id, table_id, session_type_id, created_by, guest_count, status, start_time, expires_at, price_per_guest, total_amount, created_at, updated_at
`

type ExtendSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) (DiningSession, error) {
	row := q.db.QueryRow(ctx, extendSession, arg.ID, arg.ExpiresAt)
	var i DiningSession
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.SessionTypeID,
		&i.CreatedBy,
		&i.GuestCount,
		&i.Status,
		&i.StartTime,
		&i.ExpiresAt,
		&i.PricePerGuest,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSessionByTableID = `-- name: GetActiveSessionByTableID :one
SELECT id, table_id, session_type_id, created_by, guest_count, status, start_time, expires_at, price_per_guest, total_amount, created_at, updated_at FROM dining_sessions
WHERE table_id = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveSessionByTableID(ctx context.Context, tableID pgtype.UUID) (DiningSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTableID, tableID)
	var i DiningSession
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.SessionTypeID,
		&i.CreatedBy,
		&i.GuestCount,
		&i.Status,
		&i.StartTime,
		&i.ExpiresAt,
		&i.PricePerGuest,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiningSession = `-- name: GetDiningSession :one
SELECT id, table_id, session_type_id, created_by, guest_count, status, start_time, expires_at, price_per_guest, total_amount, created_at, updated_at FROM dining_sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDiningSession(ctx context.Context, id pgtype.UUID) (DiningSession, error) {
	row := q.db.QueryRow(ctx, getDiningSession, id)
	var i DiningSession
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.SessionTypeID,
		&i.CreatedBy,
		&i.GuestCount,
		&i.Status,
		&i.StartTime,
		&i.ExpiresAt,
		&i.PricePerGuest,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDiningSessions = `-- name: ListActiveDiningSessions :many
SELECT id, table_id, session_type_id, created_by, guest_count, status, start_time, expires_at, price_per_guest, total_amount, created_at, updated_at FROM dining_sessions
WHERE status = 'active'
ORDER BY start_time DESC
`

func (q *Queries) ListActiveDiningSessions(ctx context.Context) ([]DiningSession, error) {
	rows, err := q.db.Query(ctx, listActiveDiningSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiningSession
	for rows.Next() {
		var i DiningSession
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.SessionTypeID,
			&i.CreatedBy,
			&i.GuestCount,
			&i.Status,
			&i.StartTime,
			&i.ExpiresAt,
			&i.PricePerGuest,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredSessions = `-- name: ListExpiredSessions :many
SELECT id, table_id, session_type_id, created_by, guest_count, status, start_time, expires_at, price_per_guest, total_amount, created_at, updated_at FROM dining_sessions
WHERE status = 'active' 
  AND expires_at IS NOT NULL 
  AND expires_at < NOW()
`

func (q *Queries) ListExpiredSessions(ctx context.Context) ([]DiningSession, error) {
	rows, err := q.db.Query(ctx, listExpiredSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiningSession
	for rows.Next() {
		var i DiningSession
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.SessionTypeID,
			&i.CreatedBy,
			&i.GuestCount,
			&i.Status,
			&i.StartTime,
			&i.ExpiresAt,
			&i.PricePerGuest,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiningSessionStatus = `-- name: UpdateDiningSessionStatus :one
UPDATE dining_sessions
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, table_id, session_type_id, created_by, guest_count, status, start_time, expires_at, price_per_guest, total_amount, created_at, updated_at
`

type UpdateDiningSessionStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateDiningSessionStatus(ctx context.Context, arg UpdateDiningSessionStatusParams) (DiningSession, error) {
	row := q.db.QueryRow(ctx, updateDiningSessionStatus, arg.ID, arg.Status)
	var i DiningSession
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.SessionTypeID,
		&i.CreatedBy,
		&i.GuestCount,
		&i.Status,
		&i.StartTime,
		&i.ExpiresAt,
		&i.PricePerGuest,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTableStatus = `-- name: UpdateTableStatus :exec
UPDATE dining_tables
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTableStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) error {
	_, err := q.db.Exec(ctx, updateTableStatus, arg.ID, arg.Status)
	return err
}
