// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMenuCategory = `-- name: CreateMenuCategory :one
INSERT INTO menu_categories (name, sort_order)
VALUES ($1, $2)
RETURNING id, name, sort_order, created_at
`

type CreateMenuCategoryParams struct {
	Name      string `json:"name"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateMenuCategory(ctx context.Context, arg CreateMenuCategoryParams) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, createMenuCategory, arg.Name, arg.SortOrder)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (category_id, name, description, price, image_url, is_available)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, category_id, name, description, price, image_url, is_available, created_at, updated_at
`

type CreateMenuItemParams struct {
	CategoryID  pgtype.UUID    `json:"category_id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	ImageUrl    pgtype.Text    `json:"image_url"`
	IsAvailable bool           `json:"is_available"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.ImageUrl,
		arg.IsAvailable,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.ImageUrl,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMenuItem = `-- name: GetMenuItem :one
SELECT id, category_id, name, description, price, image_url, is_available, created_at, updated_at FROM menu_items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMenuItem(ctx context.Context, id pgtype.UUID) (MenuItem, error) {
	row := q.db.QueryRow(ctx, getMenuItem, id)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.ImageUrl,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMenuCategories = `-- name: ListMenuCategories :many
SELECT id, name, sort_order, created_at FROM menu_categories
ORDER BY sort_order ASC
`

func (q *Queries) ListMenuCategories(ctx context.Context) ([]MenuCategory, error) {
	rows, err := q.db.Query(ctx, listMenuCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuCategory
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsByCategory = `-- name: ListMenuItemsByCategory :many
SELECT id, category_id, name, description, price, image_url, is_available, created_at, updated_at FROM menu_items
WHERE category_id = $1 AND is_available = TRUE
ORDER BY name ASC
`

func (q *Queries) ListMenuItemsByCategory(ctx context.Context, categoryID pgtype.UUID) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItemsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
