// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DiningSession struct {
	ID            pgtype.UUID        `json:"id"`
	TableID       pgtype.UUID        `json:"table_id"`
	SessionTypeID pgtype.UUID        `json:"session_type_id"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	GuestCount    int32              `json:"guest_count"`
	Status        string             `json:"status"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PricePerGuest pgtype.Numeric     `json:"price_per_guest"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DiningSessionType struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	IsBuffet        bool               `json:"is_buffet"`
	Price           pgtype.Numeric     `json:"price"`
	DurationMinutes pgtype.Int4        `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DiningTable struct {
	ID          pgtype.UUID        `json:"id"`
	TableNumber string             `json:"table_number"`
	Capacity    int32              `json:"capacity"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	FullName  pgtype.Text        `json:"full_name"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
