// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DiningSession struct {
	ID            pgtype.UUID        `json:"id"`
	TableID       pgtype.UUID        `json:"table_id"`
	SessionTypeID pgtype.UUID        `json:"session_type_id"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	GuestCount    int32              `json:"guest_count"`
	Status        string             `json:"status"`
	StartTime     pgtype.Timestamptz `json:"start_time"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	PricePerGuest pgtype.Numeric     `json:"price_per_guest"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DiningSessionType struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	IsBuffet        bool               `json:"is_buffet"`
	Price           pgtype.Numeric     `json:"price"`
	DurationMinutes pgtype.Int4        `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DiningTable struct {
	ID          pgtype.UUID        `json:"id"`
	TableNumber string             `json:"table_number"`
	Capacity    int32              `json:"capacity"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MenuCategory struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MenuItem struct {
	ID          pgtype.UUID        `json:"id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	IsAvailable bool               `json:"is_available"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID              pgtype.UUID        `json:"id"`
	DiningSessionID pgtype.UUID        `json:"dining_session_id"`
	Status          string             `json:"status"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID         pgtype.UUID        `json:"id"`
	OrderID    pgtype.UUID        `json:"order_id"`
	MenuItemID pgtype.UUID        `json:"menu_item_id"`
	Quantity   int32              `json:"quantity"`
	UnitPrice  pgtype.Numeric     `json:"unit_price"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	FullName  pgtype.Text        `json:"full_name"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
