// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDiningSession(ctx context.Context, arg CreateDiningSessionParams) (DiningSession, error)
	GetActiveSessionByTableID(ctx context.Context, tableID pgtype.UUID) (DiningSession, error)
	GetDiningSession(ctx context.Context, id pgtype.UUID) (DiningSession, error)
	GetSessionType(ctx context.Context, id pgtype.UUID) (DiningSessionType, error)
	ListActiveDiningSessions(ctx context.Context) ([]DiningSession, error)
	UpdateDiningSessionStatus(ctx context.Context, arg UpdateDiningSessionStatusParams) (DiningSession, error)
}

var _ Querier = (*Queries)(nil)
