// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_type.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionType = `-- name: GetSessionType :one
SELECT id, name, description, is_buffet, price, duration_minutes, created_at, updated_at FROM dining_session_types
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSessionType(ctx context.Context, id pgtype.UUID) (DiningSessionType, error) {
	row := q.db.QueryRow(ctx, getSessionType, id)
	var i DiningSessionType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsBuffet,
		&i.Price,
		&i.DurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
