// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tables.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTable = `-- name: GetTable :one
SELECT id, table_number, capacity, status, created_at, updated_at FROM dining_tables
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTable(ctx context.Context, id pgtype.UUID) (DiningTable, error) {
	row := q.db.QueryRow(ctx, getTable, id)
	var i DiningTable
	err := row.Scan(
		&i.ID,
		&i.TableNumber,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTables = `-- name: ListTables :many
SELECT id, table_number, capacity, status, created_at, updated_at FROM dining_tables
ORDER BY table_number ASC
`

func (q *Queries) ListTables(ctx context.Context) ([]DiningTable, error) {
	rows, err := q.db.Query(ctx, listTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiningTable
	for rows.Next() {
		var i DiningTable
		if err := rows.Scan(
			&i.ID,
			&i.TableNumber,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
